package org.mfi.exception;

public class QuoteAndContractException extends MfcException {

	private static final long serialVersionUID = -7326234512455998707L;

	public static enum ErrorCode {
		ERR_BIZ_QUOTECONTRACT_UNKNOWN_DURATION,
		ERR_BIZ_QUOTECONTRACT_UNKNOWN_QUOTE_STATUS,
		ERR_BIZ_QUOTECONTRACT_FORBIDDEN_QUOTE_STATUS,
		ERR_BIZ_QUOTECONTRACT_INVALID_DURATION,
		ERR_BIZ_QUOTECONTRACT_INVALID_QUOTE_STATUS,
		ERR_BIZ_QUOTECONTRACT_UNKNOWN_QUOTE,
		ERR_BIZ_QUOTECONTRACT_UNKNOWN_CONTRACT,
		ERR_BIZ_QUOTECONTRACT_UNKNOWN_VALIDATED_STATUS,
		ERR_BIZ_QUOTECONTRACT_UNKNOWN_FREQUENCY,
		ERR_BIZ_QUOTECONTRACT_INVALID_ENDVAL_AND_DURATION,
		ERR_BIZ_QUOTECONTRACT_INVALID_RENEWAL_AND_DURATION,
		ERR_BIZ_QUOTECONTRACT_UNKNOWN_INITIAL_FEE
	}

	public QuoteAndContractException(ErrorCode errorCode) {
		super(errorCode.name());
	}

	public QuoteAndContractException(ErrorCode errorCode, Object... messageArgs) {
		super(errorCode.name(), messageArgs);
	}
}
